# This is a basic workflow to help you get started with Actions

name: Download and Upload Artifact

on:
  workflow_dispatch:

jobs:
  download-upload-artifact:
    runs-on: ubuntu-latest

    steps:
    
    - name: Get latest artifact URL
      id: get-artifact
      run: |
        echo "Fetching latest artifact URL"
        LATEST_ARTIFACT_URL=$(curl -s -H "Authorization: token ${{ secrets.MY_TEST_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/HipoTech/test_repo1/actions/artifacts" \
          | jq -r '.artifacts | sort_by(.created_at) | last | .archive_download_url')
        echo "::set-output name=url::$LATEST_ARTIFACT_URL"

    - name: Download latest artifact
      run: |
        echo "Downloading latest artifact from source repository"
        curl -L -H "Authorization: token ${{ secrets.MY_TEST_PAT }}" \
          -o artifact.zip ${{ steps.get-artifact.outputs.url }}
             
    - name: Show me my dir
      run: |
        ls -R
    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: my-artifact2
    #     path: ./my-artifact.zip
    # ${{ secrets.MY_TEST_PAT }}
