# This is a basic workflow to help you get started with Actions

name: Download and Upload Artifact

on:
  workflow_dispatch:

jobs:
  download-upload-artifact:
    runs-on: ubuntu-latest

    steps:
    
    - name: Download artifact from source repository
      run: |
        mkdir download
        cd download
        echo "Downloading artifact from source repository in 'download'"
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_TEST_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/HipoTech/test_repo1/actions/artifacts/my-artifact/zip
             
    - name: Show me my dir
      run: |
        ls -R
    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: my-artifact2
    #     path: ./my-artifact.zip
