# This is a basic workflow to help you get started with Actions

name: Download and Upload Artifact

on:
  workflow_dispatch:

jobs:
  download-upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: HipoTech/test_repo1
        token: ${{ secrets.MY_TEST_PAT }}

    - name: Download artifact from source repository
      run: |
        echo "Downloading artifact from source repository in 'download'"
        cd download
        curl -H "Authorization: token ${{ secrets.MY_TEST_PAT }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -L \
             https://api.github.com/repos/HipoTech/test_repo1/actions/artifacts/my-artifact/zip
             
    - name: Show me my dir
      run: |
        ls -R
    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: my-artifact2
    #     path: ./my-artifact.zip
