name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Read and increment version
      id: version
      run: |
        PACKAGE_VERSION=$(jq -r '.version' package.json)
        NEW_VERSION=$(echo $PACKAGE_VERSION | awk -F. -v OFS=. '{$NF++;print}')
        echo "New version: $NEW_VERSION"
        jq --arg new_version $NEW_VERSION '.version = $new_version' package.json > tmp.json && mv tmp.json package.json
        echo "::set-output name=VERSION::$NEW_VERSION"
        
        PACKAGE_NAME=$(jq -r '.name' package.json)
        echo "Package name: $PACKAGE_NAME"
        RELEASE_NAME="${PACKAGE_NAME}_${NEW_VERSION}"
        echo "::set-output name=RELEASE_NAME::$RELEASE_NAME"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git config --global credential.helper store
        echo "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com" > ~/.git-credentials
        git add package.json
        git commit -m "chore: bump version to ${{ steps.version.outputs.VERSION }}"
        git push origin HEAD:main

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TEST_PAT }}
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}
        release_name: ${{ steps.version.outputs.RELEASE_NAME }}
        draft: false
        prerelease: false
