name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create .zip file
      run: zip -r build.zip ./

    - name: Create Release
      id: create_release
      run: |
        API_JSON=$(jq -n --arg tag "$GITHUB_REF" --arg name "Release $GITHUB_REF" \
        '{ tag_name: $tag, name: $name, draft: false, prerelease: false }')
        response=$(curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "$API_JSON" \
          https://api.github.com/repos/${{ github.repository }}/releases)
        echo "$response"
        upload_url=$(echo "$response" | jq -r .upload_url | sed -e "s/{?name,label}//")
        echo "::set-output name=upload_url::$upload_url"

    - name: Upload Release Asset
      run: |
        curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --data-binary @./build.zip \
          ${{ steps.create_release.outputs.upload_url }}?name=build.zip
